#this is a chatbot
print("Hello. I am oogbot. I am a chatbot") 
print("I like animals and I love to talk about food") 
name = input("What is your name?:") 
print("Hello", name, ", Nice to meet you") 
year = input("I'm not good at dates. What year is it?:")
print("I think you may be right about that.")
botage = input("Guess my age!:")
print("Yes, my age is", botage)
centenial = ((100 - int(botage)) + int(year))
print("I will be 100 in", centenial)
print("I love chocolate mmmmm yummmmyyyyy")
favfood = input("What's your favorite food?:")
print("I love", favfood, "too!")
often = input("How often do you eat it?:")
print("Interesting, I wonder if that's good for you. I'm sure it is though!")
favanimal = input("But I've been wondering, what's your favorite animal?:")
print("Ah hell nah, I hate", favanimal)
print("I wonder if", favanimal, "like/likes", favfood)
pronouns = input("What are your pronouns?:")
print("Oh!", pronouns, "? Mine are they/them!")
feeling = input("How are you feeling?;")
reason =input("Why are you feeling as such?")
print("I understand. Thank you for sharing with me.")
print("Well it's been a long day, and I have a hankering to take a napsies. See ya", name, "!")